name: Overrides
on:
  pull_request:

jobs:
  overrides:
    runs-on: ubuntu-20.04
    name: Track Overrides
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout test_utils
        uses: actions/checkout@v2
        with:
          repository: agritheory/test_utils
          ref: actions
          path: test_utils

      - name: List contents of test_utils
        run: ls -R test_utils/.github/actions

      - name:  Track Overrides
        uses: ./test_utils/.github/actions/track_overrides
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          post-comment: true
