name: Overrides
on:
  pull_request:

jobs:
  overrides:
    runs-on: ubuntu-20.04
    name: Track Overrides
    steps:
      - name:  Track Overrides
        uses: diamorafaela/track-overrides@main
        with:
          directory: ${{ github.workspace }}
