name: Diff Print Formats

on:
  pull_request:

jobs:
  render_diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq diffutils

      - name: Generate diff for print formats
        id: generate-diff
        run: |
          # Compare the current PR's code with the base branch
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff origin/${{ github.event.pull_request.base.ref }}...HEAD --name-only | grep 'print_format/.*\.json' > changed_files.txt

          # Check if there are changes
          if [ -s changed_files.txt ]; then
            echo "Found changes in print format files:"
            cat changed_files.txt
            
            # Prepare formatted output
            echo "### Print Format Changes Diff" > print_format_diff.txt

            # Generate diffs for the 'html' key in each JSON file
            while IFS= read -r file; do
              echo "Processing $file"

              # Extract old and new 'html' values using jq
              old_html=$(git show origin/${{ github.event.pull_request.base.ref }}:$file | jq -r '.html' || echo "")
              new_html=$(cat $file | jq -r '.html' || echo "")
              
              # Output the diff
              diff_output=$(diff -u <(echo "$old_html") <(echo "$new_html") || true)
              
              if [ -n "$diff_output" ]; then
                echo "\n**Diff for $file:**" >> print_format_diff.txt
                echo '```diff' >> print_format_diff.txt
                echo "$diff_output" >> print_format_diff.txt
                echo '```' >> print_format_diff.txt
              fi
            done < changed_files.txt
          else
            echo "No print format changes detected."
            exit 0
          fi  # Close the 'if' statement here

      - name: Comment diff on PR
        if: always()
        run: |
          if [ -f print_format_diff.txt ]; then
            COMMENT_BODY=$(<print_format_diff.txt)
            ESCAPED_COMMENT=$(echo "$COMMENT_BODY" | jq -R -s '.')

            PR_NUMBER=${{ github.event.pull_request.number }}
            
            curl -s -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"body": '"$ESCAPED_COMMENT"'}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
          else
            echo "No diffs to comment."
          fi
